USE Taskboard;

SELECT * FROM [USER];
SELECT * FROM [TEAM];
SELECT * FROM [TEAM_USER] ORDER BY teamId;
SELECT * FROM PROJECT;
SELECT * FROM BOARD;

SELECT * FROM [USER]  
   FOR JSON PATH

SELECT * FROM
	OPENJSON ('D:\\user.json') ;