//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taskboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_PROJECT
    {
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> projectId { get; set; }
        public Nullable<int> activityId { get; set; }
        public Nullable<int> roleId { get; set; }
    
        public virtual ACTIVITY ACTIVITY { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual ROLES ROLES { get; set; }
        public virtual USER USER { get; set; }
    }
}
