//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taskboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASKS
    {
        public int id { get; set; }
        public Nullable<int> columnId { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public byte[] attachments { get; set; }
        public string type { get; set; }
        public string priority { get; set; }
        public string severity { get; set; }
        public string asignee { get; set; }
        public Nullable<System.TimeSpan> timeToComplete { get; set; }
        public byte[] startTime { get; set; }
    
        public virtual COLUMN COLUMN { get; set; }
    }
}
