//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taskboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_TOKEN
    {
        public int id { get; set; }
        public System.Guid token { get; set; }
        public System.DateTime created { get; set; }
        public int lifeTime { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
