//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taskboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_PROFILE
    {
        public int id { get; set; }
        public string name { get; set; }
        public string about { get; set; }
        public byte[] icon { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
