USE Taskboard;

DROP TABLE USER_PROJECT;
--DROP TABLE USER_BOARD;
DROP TABLE TEAM_USER;
DROP TABLE PROJECT_SETTINGS;
DROP TABLE BOARD_SETTINGS;
DROP TABLE TASKS;
DROP TABLE "COLUMN";
DROP TABLE BOARD;
DROP TABLE ACTIVITY;
DROP TABLE PROJECT;
DROP TABLE TEAM;
--DROP TABLE ACCESS;
DROP TABLE ROLES;
DROP TABLE USER_PROFILE;
--DROP TABLE USER_SETTINGS;
DROP TABLE USER_TOKEN;
DROP TABLE "USER";